
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 23;
  public static final int MENOS = 20;
  public static final int MENOR = 25;
  public static final int CADENA = 29;
  public static final int INGRESAR = 5;
  public static final int TDECIMAL = 12;
  public static final int DECIMAL = 28;
  public static final int TCADENA = 8;
  public static final int DIVIDIDO = 22;
  public static final int COMO = 6;
  public static final int POTENCIA = 24;
  public static final int PARIZQ = 17;
  public static final int IMPRIMIR = 4;
  public static final int TBOOLEANO = 10;
  public static final int PARDER = 18;
  public static final int TNUMERO = 11;
  public static final int POR = 21;
  public static final int TCARACTER = 9;
  public static final int COMENTLINE = 14;
  public static final int CARACTER = 31;
  public static final int COMENTMULTILINE = 15;
  public static final int ASIGNACION = 16;
  public static final int FINMIENTRAS = 34;
  public static final int MAYOR = 26;
  public static final int EOF = 0;
  public static final int CONVALOR = 7;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 30;
  public static final int SALTOLINEA = 13;
  public static final int ENTERO = 27;
  public static final int MIENTRAS = 32;
  public static final int HACER = 33;
  public static final int FIN = 3;
  public static final int MAS = 19;
  public static final int INICIO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "IMPRIMIR",
  "INGRESAR",
  "COMO",
  "CONVALOR",
  "TCADENA",
  "TCARACTER",
  "TBOOLEANO",
  "TNUMERO",
  "TDECIMAL",
  "SALTOLINEA",
  "COMENTLINE",
  "COMENTMULTILINE",
  "ASIGNACION",
  "PARIZQ",
  "PARDER",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "MOD",
  "POTENCIA",
  "MENOR",
  "MAYOR",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "IDENTIFICADOR",
  "CARACTER",
  "MIENTRAS",
  "HACER",
  "FINMIENTRAS"
  };
}

